# Generated by Django 5.2.1 on 2025-07-12 06:55

import common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('production_cutting_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_with_color', to='tracking.color')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('line_type', models.CharField(choices=[('cutting', 'Cutting Line'), ('sewing', 'Sewing Line'), ('finishing', 'Finishing Line')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sequence_number', models.PositiveIntegerField(help_text='Sequential number within the order')),
                ('bundle_set_number', models.PositiveIntegerField(blank=True, help_text='Bundle set number this garment was produced from', null=True)),
                ('part_number_in_bundle', models.PositiveIntegerField(blank=True, help_text='Part number within the bundle range (e.g., 5 from 1-10)', null=True)),
                ('tracking_code', models.CharField(blank=True, help_text='Unique tracking code for this garment', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending_assembly', 'Pending Assembly'), ('issued_for_assembly', 'Issued for Assembly'), ('sewing_qc_pass', 'Sewing QC Pass'), ('sewing_qc_fail', 'Sewing QC Fail'), ('sewing_qc_rework', 'Sewing QC Rework'), ('finishing_qc_pass', 'Finishing QC Pass'), ('finishing_qc_fail', 'Finishing QC Fail'), ('finishing_qc_rework', 'Finishing QC Rework')], default='pending_assembly', max_length=20)),
                ('issued_for_assembly_at', models.DateTimeField(blank=True, help_text='When this garment was issued for assembly', null=True)),
                ('assembly_completed_at', models.DateTimeField(blank=True, help_text='When this garment completed assembly (passed sewing QC)', null=True)),
                ('finishing_completed_at', models.DateTimeField(blank=True, help_text='When this garment completed finishing (passed finishing QC)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='tracking.order')),
                ('finishing_line', models.ForeignKey(blank=True, help_text='Finishing line where this garment was finished', limit_choices_to={'line_type': 'finishing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_garments', to='tracking.productionline')),
                ('sewing_line', models.ForeignKey(blank=True, help_text='Sewing line where this garment was produced', limit_choices_to={'line_type': 'sewing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_garments', to='tracking.productionline')),
            ],
            options={
                'ordering': ['order', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bundle_number_in_spread', models.PositiveIntegerField(help_text='Bundle set number within the spread')),
                ('garment_quantity', models.PositiveIntegerField(default=1, help_text='Number of garments this bundle can produce')),
                ('part_number_start', models.PositiveIntegerField(help_text='Starting part number in the range (e.g., 1)')),
                ('part_number_end', models.PositiveIntegerField(help_text='Ending part number in the range (e.g., 10)')),
                ('tracking_code', models.CharField(blank=True, help_text='Unique tracking code for this bundle', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('issued_to_sewing', 'Issued to Sewing'), ('completed', 'Completed')], default='created', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, help_text='When this bundle was issued to sewing line.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this bundle was completed.', null=True)),
                ('fifo_violation_flag', models.BooleanField(default=False, help_text='Whether this bundle violates FIFO completion order.')),
                ('fifo_violation_details', models.JSONField(blank=True, help_text='Details about FIFO violations when bundle was completed.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='tracking.order')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='tracking.part')),
                ('assigned_sewing_line', models.ForeignKey(blank=True, help_text='Sewing line where this bundle is assigned', limit_choices_to={'line_type': 'sewing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles', to='tracking.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('rework', 'Rework')], default='pass', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('defects', models.ManyToManyField(blank=True, related_name='quality_checks', to='tracking.defect')),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='tracking.garment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('scanner_type', models.CharField(choices=[('bundle_issue', 'Bundle Issue'), ('assembly_tracking', 'Assembly Tracking'), ('sewing_qc_check', 'Sewing QC'), ('finishing_qc_check', 'Finishing QC')], max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanners', to='tracking.productionline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['production_line', 'scanner_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('event_type', models.CharField(choices=[('bundle_issued_to_sewing', 'Bundle Issued to Sewing'), ('bundle_completed', 'Bundle Completed'), ('garment_issued_for_assembly', 'Garment Issued for Assembly'), ('sewing_quality_check', 'Sewing Quality Check'), ('finishing_quality_check', 'Finishing Quality Check')], max_length=50)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.bundle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('garment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.garment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='tracking.scanner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('index', models.PositiveSmallIntegerField(default=0, help_text='Control the display order of sizes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['index', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_with_size', to='tracking.size'),
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.CharField(help_text='Spread identifier', max_length=20, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='bundle',
            name='spread',
            field=models.ForeignKey(help_text='Fabric spread this bundle was cut from', on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='tracking.spread'),
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('image', common.fields.OptimizedImageField(blank=True, null=True, upload_to='styles/')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='tracking.buyer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parts', models.ManyToManyField(blank=True, related_name='styles', to='tracking.part')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='tracking.season')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tracking.style'),
        ),
        migrations.CreateModel(
            name='PartInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_quantity', models.PositiveIntegerField(default=0, help_text='Total parts produced')),
                ('issued_quantity', models.PositiveIntegerField(default=0, help_text='Parts issued for garment assembly')),
                ('last_completed_at', models.DateTimeField(blank=True, help_text='When the last bundle was completed for this part', null=True)),
                ('average_processing_time_minutes', models.FloatField(blank=True, help_text='Average time in minutes to complete one bundle for this part', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_inventories', to='tracking.order')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='tracking.part')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('production_line', models.ForeignKey(limit_choices_to={'line_type': 'sewing'}, on_delete=django.db.models.deletion.CASCADE, related_name='part_inventories', to='tracking.productionline')),
            ],
            options={
                'indexes': [models.Index(fields=['production_line', 'order'], name='tracking_pa_product_a1ac72_idx')],
                'unique_together': {('production_line', 'order', 'part')},
            },
        ),
        migrations.AddIndex(
            model_name='garment',
            index=models.Index(fields=['order', 'bundle_set_number'], name='tracking_ga_order_i_1ce394_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='garment',
            unique_together={('order', 'sequence_number')},
        ),
        migrations.AddIndex(
            model_name='bundle',
            index=models.Index(fields=['spread', 'bundle_number_in_spread'], name='tracking_bu_spread__34f1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='bundle',
            index=models.Index(fields=['order', 'part'], name='tracking_bu_order_i_37445d_idx'),
        ),
        migrations.AddConstraint(
            model_name='bundle',
            constraint=models.UniqueConstraint(fields=('spread', 'bundle_number_in_spread', 'part'), name='unique_bundle_per_spread_part'),
        ),
        migrations.AddIndex(
            model_name='style',
            index=models.Index(fields=['buyer'], name='tracking_st_buyer_i_c448ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='style',
            unique_together={('season', 'name')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='tracking_or_order_n_887f25_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['production_cutting_date'], name='tracking_or_product_50bf60_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['style'], name='tracking_or_style_i_50aebb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_number', 'size', 'color')},
        ),
    ]
