# Generated by Django 5.2.1 on 2025-07-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='bundle_set_number',
            field=models.PositiveIntegerField(default=1, help_text='Bundle set number this garment was produced from'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garment',
            name='part_number_in_bundle',
            field=models.PositiveIntegerField(default=1, help_text='Part number within the bundle range (e.g., 5 from 1-10)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garment',
            name='status',
            field=models.CharField(choices=[('pending_assembly', 'Pending Assembly'), ('issued_for_assembly', 'Issued for Assembly'), ('in_sewing', 'In Sewing'), ('completed', 'Completed'), ('sewing_qc_pass', 'Sewing QC Pass'), ('sewing_qc_fail', 'Sewing QC Fail'), ('sewing_qc_rework', 'Sewing QC Rework'), ('finishing_qc_pass', 'Finishing QC Pass'), ('finishing_qc_fail', 'Finishing QC Fail'), ('finishing_qc_rework', 'Finishing QC Rework')], default='pending_assembly', max_length=20),
        ),
    ]
