# Generated by Django 5.2.1 on 2025-07-17 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_garment_bundle_set_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='primary_bundle',
            field=models.ForeignKey(blank=True, help_text='Primary bundle this garment is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_garments', to='tracking.bundle'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='bundle_set_number',
            field=models.PositiveIntegerField(blank=True, help_text='Bundle set number this garment was produced from', null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='part_number_in_bundle',
            field=models.PositiveIntegerField(blank=True, help_text='Part number within the bundle range (e.g., 5 from 1-10)', null=True),
        ),
    ]
