# Generated by Django 5.2.1 on 2025-07-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_style_smv_minutes_linetarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='linetarget',
            name='worker_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of workers assigned to this line for this day'),
        ),
    ]
