# Generated by Django 5.2.4 on 2025-10-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_add_worker_count_to_line_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='status',
            field=models.CharField(choices=[('pending_assembly', 'Pending Assembly'), ('issued_for_assembly', 'Issued for Assembly'), ('sewing_qc_pass', 'Sewing QC Pass'), ('sewing_qc_fail', 'Sewing QC Fail'), ('sewing_qc_rework', 'Sewing QC Rework'), ('finishing_qc_pass', 'Finishing QC Pass'), ('finishing_qc_fail', 'Finishing QC Fail'), ('finishing_qc_rework', 'Finishing QC Rework')], default='pending_assembly', max_length=20),
        ),
    ]
