# Generated by Django 5.2.4 on 2026-07-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_daily_production_report_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={'ordering': ['code', 'name']},
        ),
        migrations.AddField(
            model_name='defect',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Short defect code from the QC register, e.g. 'A', 'B', 'Aa'.", max_length=10),
        ),
    ]
