# Generated by Django 5.2.4 on 2026-07-07 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_backfill_defect_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, help_text="Optional human label, e.g. 'Production Manager'.", max_length=150)),
                ('recipient_type', models.CharField(choices=[('to', 'To'), ('cc', 'Cc')], default='to', help_text='Whether this address goes in the To or Cc field.', max_length=2)),
                ('report_type', models.CharField(choices=[('daily_production', 'Daily Production')], default='daily_production', help_text='Which automated report this recipient should receive.', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive recipients are skipped when sending.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail Recipient',
                'verbose_name_plural': 'Mail Recipients',
                'ordering': ['report_type', 'recipient_type', 'email'],
            },
        ),
    ]
