# Generated by Django 5.2.4 on 2026-07-07 06:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_mailrecipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('report_type', models.CharField(choices=[('daily_production', 'Daily Production')], default='daily_production', help_text='Which automated report this schedule controls.', max_length=32, unique=True)),
                ('send_hour', models.PositiveSmallIntegerField(default=18, help_text='Hour of day to send (0-23, Asia/Dhaka).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('send_minute', models.PositiveSmallIntegerField(default=0, help_text='Minute of the hour to send (0-59).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('is_enabled', models.BooleanField(default=True, help_text='Turn off to pause the scheduled email entirely.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedule',
            },
        ),
    ]
