# Generated by Django 5.2.4 on 2026-07-07 06:01

from django.db import migrations


def seed_daily_production_schedule(apps, schema_editor):
    """Seed the single daily_production schedule row (18:00, enabled) so the
    scheduler's behaviour is unchanged until an admin edits it."""
    ReportScheduleConfig = apps.get_model("tracking", "ReportScheduleConfig")
    ReportScheduleConfig.objects.get_or_create(
        report_type="daily_production",
        defaults={"send_hour": 18, "send_minute": 0, "is_enabled": True},
    )


def unseed_daily_production_schedule(apps, schema_editor):
    ReportScheduleConfig = apps.get_model("tracking", "ReportScheduleConfig")
    ReportScheduleConfig.objects.filter(report_type="daily_production").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_reportscheduleconfig'),
    ]

    operations = [
        migrations.RunPython(
            seed_daily_production_schedule,
            unseed_daily_production_schedule,
        ),
    ]
