# Generated by Django 5.2.4 on 2026-07-09 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_seed_report_schedule_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reason', models.CharField(blank=True, help_text='Optional note on why the bundle was transferred.', max_length=255)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='tracking.bundle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_line', models.ForeignKey(blank=True, help_text='Sewing line the bundle was on before the transfer.', limit_choices_to={'line_type': 'sewing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_transfers_out', to='tracking.productionline')),
                ('to_line', models.ForeignKey(blank=True, help_text='Sewing line the bundle was moved to.', limit_choices_to={'line_type': 'sewing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_transfers_in', to='tracking.productionline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
