# Generated by Django 5.2.4 on 2026-07-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_bundletransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='checkpoint',
            field=models.CharField(choices=[('sewing_qc', 'Sewing QC'), ('finishing_qc', 'Finishing QC')], default='sewing_qc', help_text='Which QC stage recorded this check (sewing vs finishing).', max_length=20),
        ),
    ]
