# Generated by Django 5.2.4 on 2026-07-28 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_backfill_qualitycheck_checkpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linestylecompletion',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], db_index=True, default='manual', help_text='Whether this completion was made by an operator or by the new-style-assignment / late-output triggers.', max_length=10),
        ),
        migrations.AlterField(
            model_name='linestylecompletion',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='Null for AUTO completions (no user performed them).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
